#!/bin/sh
#
# Requirements:
#    1. each identity must have already been added via ssh-add -K
#    2. the /usr/libexec/ssh-askpass script must have already been installed

set -o errexit
set -o errtrace

trap '_es=${?};
    _lo=${LINENO};
    _co=${BASH_COMMAND};
    echo "${0}: line ${_lo}: \"${_co}\" exited with a status of ${_es}";
    exit ${_es}' ERR

if [ ! -z "$1" ]; then
    echo "# Random text to cause stdin read" | ssh-add -c "$1"
else
    echo "# Random text to cause stdin read" | ssh-add -c
fi
